apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django-container
        image: your_docker_image_name:your_image_tag
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: django-db-secrets
              key: postgres-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: django-db-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-db-secrets
              key: postgres-password
